### ISSUE TITLE
keyboard shortcut problem after update to version 1.4.4

### ISSUE THREAD

**Issue by jirikrepl** [pycom/pymakr-atom#103]
Hello I am getting this error, after pressing ctrl+alt+s (for uploading the code)
Red error message pops out. Upload button works fine.

Thank you:)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'upload' of undefined

```
At /Users/jirkakrepl/.atom/packages/pymakr/lib/main.js:28

TypeError: Cannot read property 'upload' of undefined
    at HTMLElement.pymakrUpload (/packages/pymakr/lib/main.js:28:44)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:21.2.0 core:undo (input.hidden-input)
  4x -0:15 pymakr:toggleREPL (input.hidden-input)
     -0:13.4.0 pymakr:upload (input.hidden-input)
```

### Non-Core Packages

```
pymakr 1.4.4 
```
<img width="1072" alt="screen shot 2018-10-23 at 11 57 44" src="https://user-images.githubusercontent.com/2588479/47352760-e0e27a00-d6ba-11e8-9039-834cb016ee7b.png">

**Comment by RalphHogenbirk** [comment]
Found this issue, it was a small typo. Has been fixed on develop branch, will be included in the next release
