### ISSUE TITLE
Pymakr ATOM plugin install failed

### ISSUE THREAD

**Issue by aallan** [pycom/pymakr-atom#106]
Attempting to install Pymakr 1.4.5 with ATOM 1.32.2 on mac OS 10.12.6, the install fails with the following error,

Installing “pymakr@1.4.5” failed.Hide output…

npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated parser-byte-length@1.0.2: renamed to @serialport/parser-byte-length
npm WARN deprecated parser-cctalk@1.0.2: reanmed to @serialport/parser-cctalk
npm WARN deprecated parser-delimiter@1.0.2: reanmed to @serialport/parser-delimiter
npm WARN deprecated parser-readline@1.0.2: reanmed to @serialport/parser-readline
npm WARN deprecated parser-ready@1.0.2: reanmed to @serialport/parser-ready
npm WARN deprecated parser-regex@1.0.2: reanmed to @serialport/parser-regex
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

![screen shot 2018-11-17 at 02 18 13](https://user-images.githubusercontent.com/53625/48655476-1014ae80-ea0f-11e8-9aae-7474744f7aa4.png)

**Comment by aallan** [comment]
Just closed everything down and tried again. Interestingly, I got a different error. Full log file attached.

Installing “pymakr@1.4.5” failed.

npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated parser-cctalk@1.0.2: reanmed to @serialport/parser-cctalk
npm WARN deprecated parser-byte-length@1.0.2: renamed to @serialport/parser-byte-length
npm WARN deprecated parser-delimiter@1.0.2: reanmed to @serialport/parser-delimiter
npm WARN deprecated parser-ready@1.0.2: reanmed to @serialport/parser-ready
npm WARN deprecated parser-readline@1.0.2: reanmed to @serialport/parser-readline
npm WARN deprecated parser-regex@1.0.2: reanmed to @serialport/parser-regex
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at NativeModule.compile (bootstrap_node.js:596:7)
    at NativeModule.require (bootstrap_node.js:541:18)
    at net.js:45:13
    at NativeModule.compile (bootstrap_node.js:596:7)
    at NativeModule.require (bootstrap_node.js:541:18)
    at internal/child_process.js:6:13
    at NativeModule.compile (bootstrap_node.js:596:7)
    at NativeModule.require (bootstrap_node.js:541:18)
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENFILE: file table overflow, open '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/race.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:745:1)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/bluebird.js:9:36)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENFILE: file table overflow, open '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/cancel.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:730:1)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/bluebird.js:9:36)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENFILE: file table overflow, open '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/map.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:737:1)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/bluebird.js:9:36)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENFILE: file table overflow, open '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/cacache/put.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/cacache/locales/en.js:5:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/package.json'
npm WARN apm-install-dir-1181017-87972-12zbbsc.m261 No description
npm WARN apm-install-dir-1181017-87972-12zbbsc.m261 No repository field.
npm WARN apm-install-dir-1181017-87972-12zbbsc.m261 No README data
npm WARN apm-install-dir-1181017-87972-12zbbsc.m261 No license field.

npm ERR! cancel after 1 retries!
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENFILE: file table overflow, open '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/cacache/put.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/cacache/locales/en.js:5:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENFILE: file table overflow, open '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/imurmurhash/imurmurhash.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/unique-slug/index.js:3:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)

    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/chownr-4fc6ff29/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-regex-e273f7ac/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-bgblack-edc282ee/package.json'
WARNWARN  tartar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-bold-84898df3/package.json'
 ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-black-5acdc79c/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-italic-98103557/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-wrap-2f72fe6f/README.md'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-grey-13d1d2b1/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/chownr-4fc6ff29/chownr.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-regex-e273f7ac/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-regex-e273f7ac/license'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-bgblack-edc282ee/LICENSE'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-bold-84898df3/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-black-5acdc79c/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-underline-418d75a2/LICENSE'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-reset-4ef452d8/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/aws4-a9c4766d/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-italic-98103557/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/camelcase-a1da683d/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-bgyellow-9e1fe00c/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-wrap-2f72fe6f/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/chownr-4fc6ff29/README.md'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-regex-e273f7ac/readme.md'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-bgblack-edc282ee/index.js'
WARNWARN  tartar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-bold-84898df3/readme.md'
 ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/kind-of-5f572044/package.json'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-underline-418d75a2/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/aws4-a9c4766d/.travis.yml'
WARNWARN  tartar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-bgred-36525cdc/LICENSE'
 ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/camelcase-a1da683d/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/abbrev-37184ba9/abbrev.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-gray-2c6eff66/LICENSE'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/buffer-alloc-9dae77e4/index.js'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/asynckit-0c1d5719/README.md'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-black-5acdc79c/readme.md'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-reset-4ef452d8/LICENSE'
WARN tar ENFILE: file table overflow, open '/private/var/folders/c6/3ffpl3s50pdg8qkrlmcqx_v00000gp/T/apm-install-dir-1181017-87972-12zbbsc.m261/node_modules/.staging/ansi-italic-98103557/readme.md'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aa/.atom/.apm/_logs/2018-11-17T02_43_39_028Z-debug.log
[2018-11-17T02_43_39_028Z-debug.log](https://github.com/pycom/pymakr-atom/files/2591428/2018-11-17T02_43_39_028Z-debug.log)

**Comment by Xykon** [comment]
@aallan Could you please try to purge the Pymakr installation directory? Close Atom, open a Terminal and run `rm -rf ~/.atom/packages/pymakr` then start Atom again and try to install Pymakr from scratch. If that doesn't help my colleague @RalphHogenbirk will look into the issue tomorrow.

**Comment by aallan** [comment]
There doesn't seem to be any residual files in the `~/.atom/

![screen shot 2018-11-17 at 21 46 02](https://user-images.githubusercontent.com/53625/48666058-47886700-eab2-11e8-8c5d-ce4d45643060.png)
packages` directory, it's empty.

**Comment by RalphHogenbirk** [comment]
HI @aallan, i've tried some things and I don't get the same error as you get, with the same Atom and Pymakr version on mac. There is a problem with the precompiled version of serialport lib with atom v1.32.2, but it only occors after install, when activating the plugin. (There is a popup 'failed to activate plugin' with the message 'Cannot find module '@serialport/parser-byte-length'). It might be your error is related, looking at the deprication warnings, but the error that occurs on 'this._handle = new ChannelWrap();' in your stack-tracee is something I don't get.

I'll solve problem with the serialport lib today, and we'll see if that solves your error as well since it might be related. In the meantime I'd suggest checking your npm version and updating it to latest.

I'll keep you up to date

**Comment by RalphHogenbirk** [comment]
@aallan there is a fix on the develop branch right now. We're moving office so I don't have time to deploy the version today. Download it here: https://github.com/pycom/pymakr-atom/tree/develop. There is a manual in the readme on that branch for 'manual install'. 

Let me know if you have time to test the code on the dev branch. If not, I'll make sure to deploy the fix tomorrow.

**Comment by aallan** [comment]
That seems to work. I successfully installed the branch manually, and it let me connect to the board, and upload code. So… works for me! Thanks!

**Comment by RalphHogenbirk** [comment]
@aallan we released it as a new version today. So feel free to remove your manual install and switch back to the stable version, so you don't miss out on future releases.
