### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '~/Downloads/micropython-waveshare-epd...

### ISSUE THREAD

**Issue by Birillo71** [pycom/pymakr-atom#113]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.10

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/XXXXX/Downloads/micropython-waveshare-epd-master/epd/epd/'

```
At fs.js:904

Error: ENOENT: no such file or directory, scandir '/Users/XXXXX/Downloads/micropython-waveshare-epd-master/epd/epd/'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:608:28)
    at ProjectStatus.__get_local_files (/packages/pymakr/lib/board/project-status.js:88:15)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:93:20)
    at /packages/pymakr/lib/board/project-status.js:18:35)
    at /packages/pymakr/lib/board/sync.js:37:27)
    at Pymakr.sync (/packages/pymakr/lib/pymakr.js:643:22)
    at Pymakr.upload (/packages/pymakr/lib/pymakr.js:612:10)
    at /packages/pymakr/lib/pymakr.js:108:15)
    at emitNone (events.js:106:13)
    at PanelView.emit (events.js:208:7)
    at HTMLButtonElement.button_sync.onclick (/packages/pymakr/lib/main/panel-view.js:182:13)
```

### Commands

```
     -9:45.1.0 core:paste (input.hidden-input)
     -9:44.7.0 editor:newline (input.hidden-input)
  3x -9:42 core:backspace (input.hidden-input)
     -9:35.6.0 core:save (input.hidden-input)
     -8:36.3.0 pymakr:sync (div.tool-panel.tree-view)
 11x -4:07.4.0 core:backspace (input.hidden-input)
  2x -4:00.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
pymakr 1.4.10 
```

**Comment by RalphHogenbirk** [comment]
Make sure the folder you added in your 'sync_folder' config is relative to your open project and is correct. 

That being said, the error handling when adding an incorrect folder has a bug. It's been fixed in the pymakr for vscode Dev branch already, will make sure to add it to the next release for atom as well.
