### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir '~/anaconda3/bin/2to3'

### ISSUE THREAD

**Issue by PDWest** [pycom/pymakr-atom#114]
[Enter steps to reproduce:]

1. start Atom
2. select a WiPy project
3. Click Upload

btw: .../2to3 is a link to a file, viz:
phil@phils-i5 ~/anaconda3/bin $ ls -al 2*
lrwxrwxrwx 1 phil phil   8 Feb 23  2018 2to3 -> 2to3-3.5
-rwxrwxr-x 1 phil phil 108 Feb 23  2018 2to3-3.5
You guys probably know why PyMakr might be scanning that tree: I do not.  This, along w/a host of other issues is new after an upgrade from Atom 1.26

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Linux Mint
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.11

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir '/home/phil/anaconda3/bin/2to3'

```
At fs.js:904

Error: ENOTDIR: not a directory, scandir '/home/phil/anaconda3/bin/2to3'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:608:28)
    at ProjectStatus.__get_local_files (/packages/pymakr/lib/board/project-status.js:91:15)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:121:40)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:125:41)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:125:41)
    at /packages/pymakr/lib/board/project-status.js:18:35)
    at /packages/pymakr/lib/board/sync.js:37:27)
    at Pymakr.sync (/packages/pymakr/lib/pymakr.js:656:22)
    at Pymakr.upload (/packages/pymakr/lib/pymakr.js:625:10)
    at /packages/pymakr/lib/pymakr.js:106:15)
    at emitNone (events.js:106:13)
    at PanelView.emit (events.js:208:7)
    at HTMLButtonElement.button_sync.onclick (/packages/pymakr/lib/main/panel-view.js:223:13)
```

### Commands

```
     -8:55.8.0 application:reopen-project (atom-pane.pane.active)
     -8:18.8.0 core:select-right (input.hidden-input)
  2x -8:16.3.0 core:move-right (input.hidden-input)
  2x -8:15 core:backspace (input.hidden-input)
  4x -8:14.2.0 core:move-right (input.hidden-input)
     -8:12.9.0 core:select-right (input.hidden-input)
  2x -8:10.7.0 core:move-right (input.hidden-input)
  2x -8:09.4.0 core:backspace (input.hidden-input)
     -8:02.5.0 editor:newline (input.hidden-input)
  5x -7:57.4.0 core:backspace (input.hidden-input)
     -7:54.9.0 core:move-down (input.hidden-input)
     -7:54.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -7:53.6.0 editor:newline (input.hidden-input)
  5x -7:51.9.0 core:backspace (input.hidden-input)
     -7:43.4.0 core:save (input.hidden-input)
     -6:32.9.0 application:add-project-folder (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
pymakr 1.4.11 
```

**Comment by RalphHogenbirk** [comment]
Hi @PDWest, sorry for the late response. This error usually means that you've set your 'sync_folder' setting to a wrong value. Make sure this value is empty if you want to just upload your project root folder, or point it to the folder inside your open project that you want to upload (relative to the project, no leading /).

Let me know if that helps you.
