### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by RAKtronics** [pycom/pymakr-atom#115]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.11

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of null

```
At /Users/fish/.atom/packages/pymakr/lib/board/shell.js:121

TypeError: Cannot read property 'message' of null
    at retry (/packages/pymakr/lib/board/shell.js:121:16)
    at /packages/pymakr/lib/board/shell.js:147:11
    at /packages/pymakr/lib/board/shell.js:417:11
```

### Commands

```
     -6:40.9.0 editor:indent (input.hidden-input)
     -6:40.4.0 core:move-down (input.hidden-input)
     -6:40.3.0 core:move-up (input.hidden-input)
     -6:39.9.0 core:move-down (input.hidden-input)
  2x -6:39.4.0 core:backspace (input.hidden-input)
     -6:38.7.0 snippets:next-tab-stop (input.hidden-input)
     -6:38.7.0 snippets:expand (input.hidden-input)
     -6:38.7.0 editor:indent (input.hidden-input)
     -6:38.2.0 core:move-down (input.hidden-input)
  2x -6:37.6.0 core:backspace (input.hidden-input)
     -6:36.9.0 snippets:next-tab-stop (input.hidden-input)
     -6:36.9.0 snippets:expand (input.hidden-input)
     -6:36.9.0 editor:indent (input.hidden-input)
     -6:35.8.0 core:save (input.hidden-input)
     -1:43.3.0 editor:newline (input.hidden-input)
  2x -1:34.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
color-picker 2.3.0 
pymakr 1.4.11 
```

**Comment by RalphHogenbirk** [comment]
Thanks for reporting this. It's an edge case where the code handling the file upload retries wrongly assumes existence of a variable. It's been fixed now and released one minute ago under pymakr v1.4.12, together with one more hotfix that I still had pending.
