### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '~/Downloads/package/rootfs/e6c8c297a7...

### ISSUE THREAD

**Issue by JockDaRock** [pycom/pymakr-atom#120]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.1
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.13

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/jocreed/Downloads/package/rootfs/e6c8c297a7eb4bb87cdd53f61fdf8f6d7500159524eb32a256da380d1735665a/layer/bin/ash'

```
At fs.js:904

Error: ENOENT: no such file or directory, scandir '/Users/jocreed/Downloads/package/rootfs/e6c8c297a7eb4bb87cdd53f61fdf8f6d7500159524eb32a256da380d1735665a/layer/bin/ash'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:608:28)
    at ProjectStatus.__get_local_files (/packages/pymakr/lib/board/project-status.js:91:15)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:121:40)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:125:41)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:125:41)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:125:41)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:125:41)
    at ProjectStatus.__get_local_files_hashed (/packages/pymakr/lib/board/project-status.js:125:41)
    at /packages/pymakr/lib/board/project-status.js:18:35)
    at /packages/pymakr/lib/board/sync.js:37:27)
    at Pymakr.sync (/packages/pymakr/lib/pymakr.js:656:22)
    at Pymakr.upload (/packages/pymakr/lib/pymakr.js:625:10)
    at /packages/pymakr/lib/pymakr.js:106:15)
    at emitNone (events.js:106:13)
    at PanelView.emit (events.js:208:7)
    at HTMLButtonElement.button_sync.onclick (/packages/pymakr/lib/main/panel-view.js:223:13)
```

### Commands

```
```

### Non-Core Packages

```
platformio-ide-terminal 2.6.0 
pymakr 1.4.13 
```

**Comment by RalphHogenbirk** [comment]
Hi @JockDaRock, Can you give a bit more info about how this happens? It looks like it's trying to read your local folders after you click on sync, but it gets stuck on the folder '/Users/jocreed/Downloads/package/rootfs/e6c8c297a7eb4bb87cdd53f61fdf8f6d7500159524eb32a256da380d1735665a/layer/bin/ash' for some reason. Does this specific folder exist? Is it perhaps a symlink or extentionless file, or something else that's different than normal?
