### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by Girigheten** [pycom/pymakr-atom#136]
[Enter steps to reproduce:]

1. Try to install Pymakr via Atom UI

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: "openSUSE Leap
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.16

### Stack Trace

Uncaught Error: Module did not self-register.

```
At /home/peter/.atom/packages/pymakr/node_modules/bindings/bindings.js:88

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at bindings (/packages/pymakr/node_modules/bindings/bindings.js:81:44)
    at /packages/pymakr/node_modules/@serialport/bindings/lib/linux.js:1:191)
    at /packages/pymakr/node_modules/@serialport/bindings/lib/linux.js:104:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/node_modules/@serialport/bindings/lib/index.js:14:22)
    at /packages/pymakr/node_modules/@serialport/bindings/lib/index.js:17:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/node_modules/serialport/lib/index.js:2:17)
    at /packages/pymakr/node_modules/serialport/lib/index.js:17:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
```

### Commands

```
```

### Non-Core Packages

```
pymakr 1.4.16 
```

**Comment by RalphHogenbirk** [comment]
Very likely our precompiled serialport bindings file is not compatible with your openSUSE leap OS. We officially don't support that. But, you can try this:
- Run 'apm install' from the /usr/.atom/packages/pymakr folder and restart atom
- If that doesn't work, run 'apm install' again, but then remove the /usr/.atom/packages/pymakr/precompiles/serialport-linux/bindings.node file BEFORE restarting atom. (this will prevent pymakr from trying to fix the bindings file with our precompile). That will likely still get you an error, but a more useful one that might hint you to a way to rebuild it for your OS.
