### ISSUE TITLE
Pymakr plugin: "Cannot find module 'debug'"

### ISSUE THREAD

**Issue by ChuckBell** [pycom/pymakr-atom#14]
Followed instructions to install Pymakr plugin. Restarted Atom. Got this error.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [Pymakr](https://github.com/pycom/pymakr-atom) package 0.9.4

### Stack Trace

Failed to load the Pymakr package

```
At Cannot find module 'debug'

Error: Cannot find module 'debug'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Volumes/Macintosh_Data/cbell/Downloads/pymakr-atom-master/lib/connections/serialport-osx/lib/serialport.js:6:29)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Volumes/Macintosh_Data/cbell/Downloads/pymakr-atom-master/lib/connections/pyserial.js:12:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Volumes/Macintosh_Data/cbell/Downloads/pymakr-atom-master/lib/board/pyboard.js:3:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
```

### Non-Core Packages

```
Pymakr 0.9.4 
```

**Comment by ChuckBell** [comment]
Ok, after a restart, it seems to work now. :|
