### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages/pymakr/node_modules/...

### ISSUE THREAD

**Issue by fjferran** [pycom/pymakr-atom#140]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.17

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/javierferrandez/.atom/packages/pymakr/node_modules/serialport/node_modules/@serialport/bindings/lib/index.js'

```
At fs.js:143

Error: ENOENT: no such file or directory, open '/Users/javierferrandez/.atom/packages/pymakr/node_modules/serialport/node_modules/@serialport/bindings/lib/index.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Proxy.fs.readFileSync (fs.js:483:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at compileFileAtPath (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:148305)
    at Object.value [as .js] (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150943)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/node_modules/serialport/lib/index.js:2:17)
    at /packages/pymakr/node_modules/serialport/lib/index.js:17:3)
    at Module.get_Module._compile (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/lib/connections/pyserial.js:5:18)
    at /packages/pymakr/lib/connections/pyserial.js:7:30)
    at Module.get_Module._compile (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Users/javierferrandez/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/lib/board/pyboard.js:3:34)
```

### Commands

```
```

### Non-Core Packages

```
pymakr 1.4.17 
```

**Comment by elmasria** [comment]
Hello @fjferran, please try to remove the whole **pymakr** package, then install the latest **1.4.17**, see if that solves the issue.
