### ISSUE TITLE
 Uncaught Error: error: 126\?\C:\Users\Hp.atom\packages\pymakr\node_modules\@serialport\bindings\build\Release\bindings.node

### ISSUE THREAD

**Issue by ghost** [pycom/pymakr-atom#142]
(Hi! 👋  Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

## What are the steps to reproduce this issue?
1. Enable Pymakr 
2.
3.

## What happens?
An error message appears as soon as I open atom. Pymakr later did not open.

## What were you expecting to happen?
No error message

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

Error: error: 126\\?\C:\Users\Hp\.atom\packages\pymakr\node_modules\@serialport\bindings\build\Release\bindings.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Hp/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at bindings (C:\Users\Hp\.atom\packages\pymakr\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Users\Hp\.atom\packages\pymakr\node_modules\@serialport\bindings\lib\win32.js:1:191)
    at Object.<anonymous> (C:\Users\Hp\.atom\packages\pymakr\node_modules\@serialport\bindings\lib\win32.js:111:3)
    at Module.get_Module._compile (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Hp/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\Hp\.atom\packages\pymakr\node_modules\@serialport\bindings\lib\index.js:6:22)
    at Object.<anonymous> (C:\Users\Hp\.atom\packages\pymakr\node_modules\@serialport\bindings\lib\index.js:17:3)
    at Module.get_Module._compile (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Hp/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\Hp\.atom\packages\pymakr\node_modules\serialport\lib\index.js:2:17)
    at Object.<anonymous> (C:\Users\Hp\.atom\packages\pymakr\node_modules\serialport\lib\index.js:17:3)
    at Module.get_Module._compile (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Hp/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (file:///C:/Users/Hp/.atom/packages/pymakr/lib/connections/pyserial.js:5:18)
    at Object.<anonymous> (file:///C:/Users/Hp/.atom/packages/pymakr/lib/connections/pyserial.js:7:30)
    at Module.get_Module._compile (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Hp/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (file:///C:/Users/Hp/.atom/packages/pymakr/lib/board/pyboard.js:3:34)
    at Object.<anonymous> (file:///C:/Users/Hp/.atom/packages/pymakr/lib/board/pyboard.js:27:29)
    at Module.get_Module._compile (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Hp/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (C:\Users\Hp\.atom\packages\pymakr\lib\pymakr.js:15:21)
    at Object.<anonymous> (file:///C:/Users/Hp/.atom/packages/pymakr/lib/pymakr.js:18:28)
    at Module.get_Module._compile (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .js] (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/Hp/AppData/Local/atom/app-1.41.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Hp\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:146745)
    at file:///C:/Users/Hp/.atom/packages/pymakr/lib/main.js:19:20
    at file:///C:/Users/Hp/.atom/packages/pymakr/lib/main.js:73:13
    at file:///C:/Users/Hp/.atom/packages/pymakr/lib/main.js:114:13
    at ChildProcess.exithandler (child_process.js:306:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

## Any other comments?
Nothing

## What versions of software are you using?

**Operating system:**
Windows 10 x64
**Atom version:**
1.41.0 x64
**Pymakr version:**
1.4.17

**Comment by Campa123** [comment]
Confirmed, on Atom 1.39.1 Pymakr works!

**Comment by elmasria** [comment]
Hello, Kindly note that we have a new version now 1.4.18 that will fix that issue. try to update the **pymakr** package

**Comment by Campa123** [comment]
@elmasria Yes with the latest version it works without problems. Thank you!

**Comment by michelmans** [comment]
> Hello, Kindly note that we have a new version now 1.4.18 that will fix that issue. try to update the **pymakr** package

I've updated to Pymakr 1.4.18 and using 1.41.0 x64 Atom and still receiving the same error. I am using windows 10 pro.
