### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\$ATOM_HOME\packages\pymakr\node_mod...

### ISSUE THREAD

**Issue by teuler** [pycom/pymakr-atom#143]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.17

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\teuler\.atom\packages\pymakr\node_modules\@serialport\bindings\build\Release\bindings.node

```
At C:\Users\teuler\.atom\packages\pymakr\node_modules\bindings\bindings.js:88

Error: The specified module could not be found.
\\?\C:\Users\teuler\.atom\packages\pymakr\node_modules\@serialport\bindings\build\Release\bindings.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at bindings (/packages/pymakr/node_modules/bindings/bindings.js:81:44)
    at /packages/pymakr/node_modules/@serialport/bindings/lib/win32.js:1:191)
    at /packages/pymakr/node_modules/@serialport/bindings/lib/win32.js:111:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/node_modules/@serialport/bindings/lib/index.js:6:22)
    at /packages/pymakr/node_modules/@serialport/bindings/lib/index.js:17:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/node_modules/serialport/lib/index.js:2:17)
    at /packages/pymakr/node_modules/serialport/lib/index.js:17:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
```

### Commands

```
```

### Non-Core Packages

```
pymakr 1.4.17 
```

**Comment by elmasria** [comment]
Hello @teuler, Kindly note that we have a new version now 1.4.18 that will fix that issue. try to update the **pymakr** package

**Comment by teuler** [comment]
Thanks!
