### ISSUE TITLE
Uncaught Error: Cannot find module './utils/CircularList'

### ISSUE THREAD

**Issue by Mariana-Andrade-Alves** [pycom/pymakr-atom#148]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.18

### Stack Trace

Uncaught Error: Cannot find module './utils/CircularList'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module './utils/CircularList'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/node_modules/xterm/lib/Buffer.js:3:22)
    at /packages/pymakr/node_modules/xterm/lib/Buffer.js:98:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/node_modules/xterm/lib/BufferSet.js:13:16)
    at /packages/pymakr/node_modules/xterm/lib/BufferSet.js:67:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/pymakr/node_modules/xterm/lib/xterm.js:3:19)
    at /packages/pymakr/node_modules/xterm/lib/xterm.js:1580:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
```

### Non-Core Packages

```
pymakr 1.4.18 
```

**Comment by elmasria** [comment]
Hello @Mariana-Andrade-Alves, try to do the below:
1. close Atom
2. delete `pymakr` folder under `C:\Users\maria\.atom\packages\`
3. restart your pc
4. install `pymakr` again
