### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not ...

### ISSUE THREAD

**Issue by AllTracking** [pycom/pymakr-atom#201]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 7 Professional N 
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 2.1.2

### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

```
At C:\Users\Engineer\.atom\packages\pymakr\node_modules\xterm\lib\xterm.js:1

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at t.dispose (/packages/pymakr/node_modules/xterm/lib/xterm.js:1:215082)
    at t.dispose (/packages/pymakr/node_modules/xterm/lib/xterm.js:1:234675)
    at t.dispose (/packages/pymakr/node_modules/xterm/lib/xterm.js:1:107782)
    at e.dispose (/packages/pymakr/node_modules/xterm/lib/xterm.js:1:99263)
    at Device.close (/packages/pymakr/lib/connections/device.js:195:25)
    at Pymakr.removeDevice (/packages/pymakr/lib/pymakr.js:497:19)
    at /packages/pymakr/lib/pymakr.js:346:13)
    at PanelView.emit (events.js:182:13)
    at /packages/pymakr/lib/views/panel-view.js:509:13)
    at HTMLDivElement.dispatch (/packages/pymakr/node_modules/jquery/dist/jquery.js:5429:27)
    at HTMLDivElement.elemData.handle (/packages/pymakr/node_modules/jquery/dist/jquery.js:5233:28)
```

### Commands

```
     -1:57.6.0 core:paste (input.hidden-input)
     -1:56.4.0 core:save (input.hidden-input)
     -1:42.4.0 core:paste (input.hidden-input)
     -1:41.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
my-package 0.0.0 
pymakr 2.1.2 
script 3.26.0 
```

**Comment by pedroknup** [comment]
This problem has been fixed with today's update of Pymakr (2.1.4). Please update your Pymakr Atom :)
