### ISSUE TITLE
Uncaught TypeError: _this.pyboard.enterFriendlyRepl_non_blocking is not a function

### ISSUE THREAD

**Issue by smbunn** [pycom/pymakr-atom#217]
[Enter steps to reproduce:]

1. just started new project upload sync for first time.
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 2.1.5

### Stack Trace

Uncaught TypeError: _this.pyboard.enterFriendlyRepl_non_blocking is not a function

```
At C:\Users\Simon\.atom\packages\pymakr\lib\features\sync\sync.js:606

TypeError: _this.pyboard.enterFriendlyRepl_non_blocking is not a function
    at /packages/pymakr/lib/features/sync/sync.js:606:21
    at /packages/pymakr/lib/features/sync/sync.js:826:7
    at finish (/packages/pymakr/lib/board/shell.js:537:9)
    at /packages/pymakr/lib/connections/pytelnet.js:95:15
    at Telnet.write (/packages/pymakr/lib/connections/telnet/util-telnet.js:192:5)
    at TelnetClient.write (/packages/pymakr/lib/connections/telnet/telnetcli.js:211:14)
    at PyTelnet.send_raw (/packages/pymakr/lib/connections/pytelnet.js:94:17)
    at PyTelnet.send (/packages/pymakr/lib/connections/pytelnet.js:90:10)
    at Pyboard.send (/packages/pymakr/lib/board/pyboard.js:527:21)
    at Pyboard.softResetNoFollow (/packages/pymakr/lib/board/pyboard.js:201:10)
    at /packages/pymakr/lib/board/shell.js:374:21
    at /packages/pymakr/lib/board/pyboard.js:652:9
    at /packages/pymakr/lib/connections/pytelnet.js:95:15
    at Telnet.write (/packages/pymakr/lib/connections/telnet/util-telnet.js:192:5)
    at TelnetClient.write (/packages/pymakr/lib/connections/telnet/telnetcli.js:211:14)
    at PyTelnet.send_raw (/packages/pymakr/lib/connections/pytelnet.js:94:17)
    at Pyboard.sendRaw (/packages/pymakr/lib/board/pyboard.js:644:21)
    at Pyboard.execRawNoReset (/packages/pymakr/lib/board/pyboard.js:650:10)
    at Shell.reset (/packages/pymakr/lib/board/shell.js:372:18)
    at Shell.cleanClose (/packages/pymakr/lib/board/shell.js:545:12)
    at /packages/pymakr/lib/board/shell.js:494:13
    at Shell.stopWorking (/packages/pymakr/lib/board/shell.js:522:7)
    at Shell.exit (/packages/pymakr/lib/board/shell.js:493:10)
    at Sync.exit (/packages/pymakr/lib/features/sync/sync.js:825:16)
    at Sync.throwError (/packages/pymakr/lib/features/sync/sync.js:605:10)
    at /packages/pymakr/lib/features/sync/sync.js:243:17
    at /packages/pymakr/lib/board/pyboard.js:258:11
    at /packages/pymakr/lib/board/pyboard.js:632:11
```

### Commands

```
     -1:55.6.0 core:delete (input.hidden-input)
     -1:41.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
kite 0.185.0 
pymakr 2.1.5 
```

**Comment by pedroknup** [comment]
Hi @smbunn. You can expect an update soon with a fix for that (and a some more fixes and features) with the next Pymakr Atom update (2.1.4).

An alternative for that is cloning this repository, checking the develop branch and entering the following commands on terminal (under the cloned repository directory): `apm install && apm link`. This will install Pymakr from the repository, instead of the Atom's packages section. Remember: for that you will need to uninstall your current Pymakr.
