### ISSUE TITLE
Uncaught TypeError: _this.pymakr.sync is not a function

### ISSUE THREAD

**Issue by moiraghan** [pycom/pymakr-atom#252]
steps to reproduce:

1. Synchronise project with Pymakr

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.5
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 2.1.12

### Stack Trace

Uncaught TypeError: _this.pymakr.sync is not a function

```
At /home/kb00456/.atom/packages/pymakr/lib/main.js:45

TypeError: _this.pymakr.sync is not a function
    at HTMLElement.pymakrSync (/packages/pymakr/lib/main.js:45:47)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349392)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:347867)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:718771)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:726694)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -5:59.2.0 pymakr:sync (input.hidden-input)
     -5:48.2.0 application:new-file (div.panels-item)
     -5:24.5.0 core:backspace (input.hidden-input)
  4x -5:21.1.0 editor:newline (input.hidden-input)
     -5:11.7.0 core:backspace (input.hidden-input)
  2x -5:09.0 editor:newline (input.hidden-input)
     -4:53.7.0 core:backspace (input.hidden-input)
     -4:46.2.0 core:move-right (input.hidden-input)
     -4:44.6.0 editor:toggle-line-comments (input.hidden-input)
     -4:42.8.0 core:save (input.hidden-input)
     -4:16.2.0 pymakr:sync (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
haskell-debug 0.3.6 
ide-haskell 2.4.1 
language-haskell 1.19.2 
pymakr 2.1.12 
```

**Comment by elmasria** [comment]
@moiraghan, I think this will be solved either by update Atom to the latest version or Downgrade Pymakr to the last version you were using.
