### ISSUE TITLE
latest Pymakr 2.1.13 could not be installed with latest Atom 1.57.0 

### ISSUE THREAD

**Issue by ClemensGruber** [pycom/pymakr-atom#255]
Even the update from Atom 1.56 to 1.57 did not change anything, still not possible to install Pymakr!? What a creePy support from PyCom! Tons of bug issues but no reaction! We will leave the PyCom universe, too much hassle, less support. 

```
Installing “pymakr@2.1.13” failed.Hide output…

> @serialport/bindings@8.0.8 install C:\Users\mail\AppData\Local\Temp\apm-install-dir-2021411-1496-16xfu09.pesh\node_modules\pymakr\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild


C:\Users\mail\AppData\Local\Temp\apm-install-dir-2021411-1496-16xfu09.pesh\node_modules\pymakr\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated parser-byte-length@1.0.2: renamed to @serialport/parser-byte-length
npm WARN deprecated parser-cctalk@1.0.2: reanmed to @serialport/parser-cctalk
npm WARN deprecated parser-delimiter@1.0.2: reanmed to @serialport/parser-delimiter
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated parser-readline@1.0.2: reanmed to @serialport/parser-readline
npm WARN deprecated parser-ready@1.0.2: reanmed to @serialport/parser-ready
npm WARN deprecated parser-regex@1.0.2: reanmed to @serialport/parser-regex
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
prebuild-install WARN install No prebuilt binaries found (target=9.4.4 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\mail\AppData\Local\atom\app-1.57.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Users\\mail\\AppData\\Local\\atom\\app-1.57.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\mail\\AppData\\Local\\atom\\app-1.57.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mail\AppData\Local\Temp\apm-install-dir-2021411-1496-16xfu09.pesh\node_modules\pymakr\node_modules\@serialport\bindings
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for pymakr@2.1.13: wanted: {"atom":">=1.41.0","node":">=6.3.0 <=7.0.0"} (current: {"node":"12.14.1","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: pymakr@2.1.13
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\mail\AppData\Local\Temp\apm-install-dir-2021411-1496-16xfu09.pesh\package.json'
npm WARN apm-install-dir-2021411-1496-16xfu09.pesh No description
npm WARN apm-install-dir-2021411-1496-16xfu09.pesh No repository field.
npm WARN apm-install-dir-2021411-1496-16xfu09.pesh No README data
npm WARN apm-install-dir-2021411-1496-16xfu09.pesh No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@8.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mail\.atom\.apm\_logs\2021-05-11T14_15_04_025Z-debug.log
```

**Comment by elmasria** [comment]
Hi @ClemensGruber,

Thank you for reporting this. and I am sorry for the bad experience you are facing. We are trying to keep our product up-to-date. However, Atom's changes will require additional effort on our part, which sometimes takes time. I would be happy to help you if the below solution did not work for you. 

I have checked this on multiple environments. 

After the latest upgrade of Atom, the **serialport** package (and because we are still using version *8.0.x*) tries to rebuild based on the new electron version (used by Atom on version 1.57). As a result, **Pymakr** may throw issues on environments that miss some setup, like the error you mentioned. 

One solution is by doing the below setup for windows users to use `Pymakr.

Steps:
* Install Python 2.x.x (https://www.python.org/downloads/release/python-2718/). 
   If you already have python installed, make sure you add it to the environment variable.
* Download Microsoft Visual C++ (2017 or later). (https://stackoverflow.com/a/54136652) 
![image](https://user-images.githubusercontent.com/12611535/118454633-dfee1980-b6f8-11eb-996f-c2d771d0f8f8.png)


The following link will have two solutions, one I mentioned above and an alternative. But the (windows-build-tools) option did not work for me on two different Pcs.
https://stackoverflow.com/a/59882818

We will work on updating   **serialport** package to avoid this type of issue in the future.

**Comment by ClemensGruber** [comment]
I had to use Pymakr as I filed the bug, so 6 days ago! I had no time in the projekt to wait for an update to use your products. So I uninstalled Atom und installed VSCode with Pymakr. Hope this will last with less bugs as long as we use PyCom products mit MicroPython.
