### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'pymakr/lib/python/minified/monitor.py'

### ISSUE THREAD

**Issue by cparrish60** [pycom/pymakr-atom#62]
upload file

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.2.7

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'pymakr/lib/python/minified/monitor.py'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'pymakr/lib/python/minified/monitor.py'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at /packages/pymakr/lib/board/monitor.js:20:19)
    at Sync.start_monitor (/packages/pymakr/lib/board/sync.js:552:20)
    at Sync.__start_sync (/packages/pymakr/lib/board/sync.js:187:10)
    at Sync.start (/packages/pymakr/lib/board/sync.js:139:10)
    at Pymakr.sync (/packages/pymakr/lib/pymakr.js:324:22)
    at /packages/pymakr/lib/pymakr.js:58:15)
    at emitNone (events.js:86:13)
    at PanelView.emit (events.js:185:7)
    at HTMLButtonElement.PanelView.button_sync.onclick (/packages/pymakr/lib/main/panel-view.js:107:13)
```

### Commands

```
```

### Non-Core Packages

```
pymakr 1.2.7 
```

**Comment by JVGD** [comment]
Hi! Just had the same problem with the same output. For me the problem was that I had a single file inside of my project folder, but for uploading you need to have at least these two files:

- boot.py
- main.py

Hope this helps
