### ISSUE TITLE
Cannot install on Atom 1.23.3 x64 (archlinux)

### ISSUE THREAD

**Issue by DoNck** [pycom/pymakr-atom#63]
Hi,

I tried installing Pymakr from  "install new package" within Atom.

```
Installing “pymakr@1.2.7” failed.Hide output…
(node:19032) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at _errnoException (util.js:1003:13)
    at Socket._read (net.js:495:20)
    at Socket.Readable.read (_stream_readable.js:449:10)
    at Socket.read (net.js:376:43)
    at new Socket (net.js:259:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at Object.exports.spawn (child_process.js:499:9)
    at Install.module.exports.Command.spawn (/usr/lib/node_modules/atom-package-manager/lib/command.js:31:31)
    at Install.module.exports.Command.fork (/usr/lib/node_modules/atom-package-manager/lib/command.js:62:25)
    at Install.module.exports.Install.installNode (/usr/lib/node_modules/atom-package-manager/lib/install.js:104:19)
    at Install.installNode (/usr/lib/node_modules/atom-package-manager/lib/install.js:3:59)
    at /usr/lib/node_modules/atom-package-manager/lib/install.js:458:30
    at fn (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:756:18)
14,037
```

I tried uninstalling atom and apm, rm -Rf ~/.atom, reinstalling atom, nothing came out better.

I'm using atom-1.23.3-1 and apm-1.19.0-1.

Interesting, apm -v fails the same way:

```
[jeff@laptaupe ~]$ apm -v
(node:19792) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at _errnoException (util.js:1003:13)
    at Socket._read (net.js:495:20)
    at Socket.Readable.read (_stream_readable.js:449:10)
    at Socket.read (net.js:376:43)
    at new Socket (net.js:259:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at exports.spawn (child_process.js:499:9)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/atom-package-manager/lib/apm-cli.js:170:17)
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

**Comment by DoNck** [comment]
A system upgrade fixed the issue, similar to:
https://github.com/hexojs/hexo/issues/2970

updated:
```
extra/libuv            1.19.0-1 1 -> 2
core/linux-lts         4.9.76-1 -> 4.9.77-1
core/linux-lts-headers 4.9.76-1 -> 4.9.77-1
extra/ardour           5.9-2    -> 5.12-2
extra/git              2.15.1-2 -> 2.16.0-1
extra/liblo            1:0.28-1 -> 1:0.29-1
extra/rsync            3.1.2-8  -> 3.1.3pre1-1
```
Comparing with the other ticket, it should be related to either git or libuv.

Closing the issue.
