### ISSUE TITLE
Failed to reload Pymakr 1.2.10

### ISSUE THREAD

**Issue by liowmei** [pycom/pymakr-atom#72]
I have Atom version of 1.25.0 and Pymakr version 1.2.10. But fail to load the Pymakr package

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 8.1 Single Language
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.2.10

### Stack Trace

Failed to load the pymakr package

```
At Could not locate the bindings file. Tried:
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\build\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\build\Debug\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\build\Release\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\out\Debug\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\Debug\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\out\Release\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\Release\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\build\default\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\compiled\7.9.0\win32\x64\serialport.node

Error: Could not locate the bindings file. Tried:
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\build\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\build\Debug\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\build\Release\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\out\Debug\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\Debug\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\out\Release\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\Release\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\build\default\serialport.node
 → C:\Users\user\.atom\packages\Pymakr\node_modules\bindings\compiled\7.9.0\win32\x64\serialport.node
    at bindings (/packages/Pymakr/node_modules/bindings/bindings.js:88:9)
    at /packages/Pymakr/precompiles/serialport-win/lib/bindings.js:3:35)
    at /packages/Pymakr/precompiles/serialport-win/lib/bindings.js:36:3)
    at Module.get_Module._compile (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Pymakr/precompiles/serialport-win/lib/serialport.js:12:25)
    at /packages/Pymakr/precompiles/serialport-win/lib/serialport.js:476:3)
    at Module.get_Module._compile (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/pymakr/lib/connections/pyserial.js:21:18)
    at /packages/pymakr/lib/connections/pyserial.js:27:30)
    at Module.get_Module._compile (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (C:/Users/user/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/pymakr/lib/board/pyboard.js:3:34)
    at /packages/pymakr/lib/board/pyboard.js:25:29)
```

### Commands

```
```

### Non-Core Packages

```
pymakr 1.2.10 
```

**Comment by RalphHogenbirk** [comment]
I posted an answer in this topic, before I spotted this new issue: https://github.com/pycom/pymakr-atom/issues/1#issuecomment-373888130
