### ISSUE TITLE
Uncaught TypeError: Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by jirikrepl** [pycom/pymakr-atom#90]
Hi Ralph, I see this today after I click on upload button. I tried to restart Atom but I still have this error message. Thank you

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Mac OS X 10.13.5
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'info' of undefined

```
At /Users/jirkakrepl/.atom/packages/pymakr/lib/board/pyboard.js:166

TypeError: Cannot read property 'info' of undefined
    at /packages/pymakr/lib/board/pyboard.js:166:19
    at /packages/pymakr/lib/board/pyboard.js:498:11
```

### Commands

```
     -3:55.7.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -3:54.4.0 core:close (input.hidden-input)
     -3:53.7.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
  2x -0:18.4.0 pymakr:toggleREPL (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
pymakr 1.4.0 
```

![screen shot 2018-07-12 at 11 05 09](https://user-images.githubusercontent.com/2588479/42623587-897bacca-85c3-11e8-9f0b-b2bf48ad18b8.png)

**Comment by jirikrepl** [comment]
I have to reconnect USB cable and reconnect device in PyMakr, then I can upload files.
